### ISSUE TITLE
Length Problem

### ISSUE THREAD

**Issue by joaoflope** [devtomas2003/LeagueOfHeroes#1]
https://github.com/devtomas2003/LeagueOfHeroes/blob/bc92b5f5a58670ddef16dfe8ec84e052fbd6949f/src/Views/SuperHeroForm.jsx#L65C32-L65C32

lastHeroes[lastHeroes.length-1].id+1

**Comment by devtomas2003** [comment]
Bug Fixed! Will be available in the next publish!
