### ISSUE TITLE
Edit Problem

### ISSUE THREAD

**Issue by joaoflope** [devtomas2003/LeagueOfHeroes#2]
https://github.com/devtomas2003/LeagueOfHeroes/blob/bc92b5f5a58670ddef16dfe8ec84e052fbd6949f/src/Views/SuperHeroForm.jsx#L46

listOfHeroes[listOfHeroes.findIndex((listOfAllHeroes) => { return(listOfAllHeroes.id === parseInt(id)) })]

**Comment by devtomas2003** [comment]
Bug Fixed! Will be available in the next publish!
